<a href="https://colab.research.google.com/github/routparam12/Python_qns/blob/main/Panelist_behaviour_check.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel('/content/PanelistAug.xlsx')

In [5]:
df.head()

,panelistId,firstName,lastName,gender,countryId,age,zipCode,email,joinDate,sourceId,ipFraudScore
0,99712,Ronald,Martin,Male,4,47,45133,heskamran4@gmail.com,2025-07-10 21:50:54.353 +0530,[NULL],[NULL]
1,91989,Jakub,Olszewski,Mężczyzna,24,19,17-132,1748613780618_gamekrzywy@gmail.com,2025-05-30 19:30:03.367 +0530,[NULL],[NULL]
2,170603,Sawyer,Mitchell,Male,4,48,28403,sawyermitchell512@gmail.com,2026-07-27 21:56:43.244 +0530,[NULL],0
3,130216,Ahad,Lukas,Male,4,41,42069,zntee1996@gmail.com,2025-11-19 16:42:58.936 +0530,25,[NULL]
4,6827,Alexis,Wynn,Female,4,17,75141,alexiswynn84@gmail.com,2023-10-25 18:02:31.455 +0530,31,[NULL]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 171413 entries, 0 to 171412
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   panelistId    171413 non-null  int64
 1   firstName     171411 non-null  object
 2   lastName      171398 non-null  object
 3   gender        171413 non-null  object
 4   countryId     171413 non-null  int64
 5   age           171413 non-null  int64
 6   zipCode       171411 non-null  object
 7   email         171413 non-null  object
 8   joinDate      171413 non-null  object
 9   sourceId      171413 non-null  object
 10  ipFraudScore  171413 non-null  object
dtypes: int64(3), object(8)
memory usage: 14.4+ MB

In [7]:
df.isnull().sum()

panelistId       0
firstName        2
lastName        15
gender           0
countryId        0
age              0
zipCode          2
email            0
joinDate         0
sourceId         0
ipFraudScore     0
dtype: int64

In [8]:
df.describe()

          panelistId      countryId            age
count  171413.000000  171413.000000  171413.000000
mean    86984.539947       4.519284      40.139803
std     50224.678768       4.092794      12.327130
min         4.000000       1.000000       0.000000
25%     43285.000000       4.000000      31.000000
50%     87161.000000       4.000000      40.000000
75%    130661.000000       4.000000      47.000000
max    173629.000000      34.000000     582.000000

In [9]:
print(df['sourceId'].value_counts(dropna=False).head(20))

sourceId
[NULL]    88943
22        16264
11        13374
25        11348
24         4986
50         4977
31         4770
21         4459
39         4049
40         3549
29         3372
10         2196
37         1298
28         1015
56          966
67          816
38          803
35          727
49          570
54          379
Name: count, dtype: int64

In [10]:
print(df['ipFraudScore'].unique()[:20])

['[NULL]' 0 70 84 73 38 100 79 15 82 44 12 75 91 94 90 87 77 88 97]

In [11]:
print(df['joinDate'].head())

0    2025-07-10 21:50:54.353 +0530
1    2025-05-30 19:30:03.367 +0530
2    2026-07-27 21:56:43.244 +0530
3    2025-11-19 16:42:58.936 +0530
4    2023-10-25 18:02:31.455 +0530
Name: joinDate, dtype: object

In [12]:
df['joinDate'] = pd.to_datetime(df['joinDate'], errors='coerce')
print("unparsed dates:", df['joinDate'].isna().sum())

unparsed dates: 0